[project]
name = "information_retrieval"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "==3.12.0"
dependencies = [
    "black==25.9.0",
    "gensim>=4.4.0",
    "nltk>=3.9.2",
    "scikit-learn>=1.7.2",
]
